Resources:
  S3PracticeRole262602C0:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              AWS:
                Fn::Join:
                  - ""
                  - - "arn:"
                    - Ref: AWS::Partition
                    - :iam::s3-tutorials:root
        Version: "2012-10-17"
    Metadata:
      aws:cdk:path: S3Stack/S3PracticeRole/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/zPSMzQy0zNQTCwv1k1OydbNyUzSqw4uSUzO1gEKxWcm5upVB+XnpOo4p+WB6FqdoNTi/NKiZIgIlF2rE1BZkpGfp2+sZ2ioZ66YVZyZqVtUmleSmZuqFwShAbeUlMZqAAAA
    Metadata:
      aws:cdk:path: S3Stack/CDKMetadata/Default
Parameters:
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]
Rules:
  CheckBootstrapVersion:
    Assertions:
      - Assert:
          Fn::Not:
            - Fn::Contains:
                - - "1"
                  - "2"
                  - "3"
                  - "4"
                  - "5"
                - Ref: BootstrapVersion
        AssertDescription: CDK bootstrap stack version 6 required. Please run 'cdk bootstrap' with a recent version of the CDK CLI.
