name: Jupyter Notebook Format Check

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nbQA flake8

    - name: Check notebook format with flake8
      run: |
        nbqa flake8 **/*.ipynb --max-line-length=99

    - name: Check notebook format with black
      run: |
        nbqa black **/*.ipynb --check --diff --line-length 99

    - name: Check python code format with flake8
      run: |
        flake8 . --count --show-source --statistics --ignore=W605,W503,E501
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --statistics

    - name: Check python code format with black
      run: |
        conda install -c conda-forge black=20.8b1
        black . --check --diff --target-version py37 --line-length 99
    
    - name: Check documentation coverage with Interrogate
      run: |
        conda install -c conda-forge interrogate
        interrogate . -c pyproject.toml