name: Jupyter Notebook Format Check

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nbQA flake8 black interrogate

    - name: Check notebook format with flake8
      if: always()
      run: |
        nbqa flake8 **/*.ipynb --count --exit-zero --max-complexity=10 --statistics --ignore=W605,W503,E501,E203 --max-line-length=99

    - name: Check notebook format with black
      if: always()
      run: |
        nbqa black **/*.ipynb --check --diff --line-length 99

    - name: Check python code format with flake8
      if: always()
      run: |
        flake8 . --count --exit-zero --max-complexity=10 --show-source --statistics --ignore=W605,W503,E501,E203 --max-line-length=99  

    - name: Check python code format with black
      if: always()
      run: |
        black . --check --diff --line-length 99
    
    - name: Check documentation coverage with Interrogate
      if: always()
      run: |
        interrogate . -c pyproject.toml